### ISSUE TITLE
Use a minimax approximation

### ISSUE THREAD

**Issue by simonbyrne** [oscardssmith/BetterExp.jl#1]
You can further reduce the polynomial error using minimax polynomials instead of Taylor series. Using the [Remez.jl](https://github.com/simonbyrne/Remez.jl) package:
```
using Remez
N,D,E,X = ratfn_minimax(expm1, (-1/512,1/512), 4, 0)
```
and rounding the first coefficient to zero gives the coefficients:
```
 P = (0.0, 0.9999999999999621, 0.49999999999998357, 0.16666670640310027, 0.04166667593850114)
```

This has maximal approximation error on the interval [-1/512,1/512] of `1.5e-17`, vs `2.1e-16` of the Taylor series.

**Comment by oscardssmith** [comment]
I'm already doing this. I think the difference between your version and mine is that I cider coefficients to minimize the error of `expm1(x)/x`, as otherwise I want reliable getting a zero for the first coefficient. Does using your set of coefficients lead to better error for the function as a whole?

**Comment by simonbyrne** [comment]
I get slightly different coefficients (and lower error) if I do it for `expm1(x)/x`:
```
julia> N,D,E,X = ratfn_minimax(x -> x == 0 ? one(x) : expm1(x)/x, (-1/512,1/512), 3, 0);

julia> P = (0.0,Float64.(N)...)
(0.0, 0.9999999999999848, 0.4999999999999899, 0.16666669845581322, 0.04166667461395329)
```
However it depends on your weighting function. In this case you probably want to minimize the absolute error of `expm1(x)` instead of `expm1(x)/x` (unless you actually want an `expm1` function, but the error of these approximations is still too large for that), so we should weight it by `x`, which gives similar coefficients to my original comment above:
```
julia> N,D,E,X = ratfn_minimax(x -> x == 0 ? one(x) : expm1(x)/x, (-1/512,1/512), 3, 0,(x,y) -> x);

julia> P = (0.0,Float64.(N)...)
(0.0, 0.9999999999999621, 0.4999999999999987, 0.16666670640827344, 0.04166667064082726)
```

Here's a plot of the error:
![image3](https://user-images.githubusercontent.com/1692009/89803710-0c309600-dae8-11ea-831c-f0dfd5933ded.png)

**Comment by oscardssmith** [comment]
These numbers were slightly off as the bounds should have been `log(2)/512` not `1/512`, but this does lead to an improvement. Max error goes from .785 to .755 ULPs.
Edit: This also allows for lowering the number of terms for `exp10` without increased error.

**Comment by simonbyrne** [comment]
nice!
