### ISSUE TITLE
Add to general registry

### ISSUE THREAD

**Issue by oscardssmith** [oscardssmith/BetterExp.jl#2]
@JuliaRegistrator register

**Comment by chriselrod** [comment]
Try again after installing the [GitHub Registrator.jl app](https://github.com/JuliaRegistries/Registrator.jl)?

**Comment by oscardssmith** [comment]
Ah. I missed that step.

**Comment by oscardssmith** [comment]
@JuliaRegistrator register

**Comment by oscardssmith** [comment]
@JuliaRegistrator register
