### ISSUE TITLE
exp at ±Inf

### ISSUE THREAD

**Issue by visr** [oscardssmith/BetterExp.jl#3]
Thanks for working on this problem!

Not sure if you are aware, but I wanted to call your attention to a difference in behavior with `Base.exp` at the infinities. The following goes for both `Float64` and `Float32`. Whereas `Base.exp` returns `0.0` and `Inf` at respectively `-Inf` and `Inf`, `BetterExp.exp` returns `NaN` in both cases.

```julia
julia> using BetterExp

# different
julia> Base.exp(-Inf)
0.0

julia> Base.exp(Inf)
Inf

julia> BetterExp.exp(-Inf)
NaN

julia> BetterExp.exp(Inf)
NaN

# this seems fine however
julia> BetterExp.exp(-999.0) == Base.exp(-999.0) == 0.0
true

julia> BetterExp.exp(999.0) == Base.exp(999.0) == Inf
true
```

**Comment by oscardssmith** [comment]
That's surprising since I have an explicit inf check. I'll fix it tonight.

**Comment by oscardssmith** [comment]
Took a little longer than expected, but this is fixed.
